### ISSUE TITLE
URL query `mkSem` for the class of even semester.

### ISSUE THREAD

**Issue by albugowy15** [theodorusclarence/its-class-helper#4]
Currently, the URL query parameter `mkSem` is set to `1` for all classes and semesters. However, it only functions correctly for classes with odd semesters. For classes with even semesters, the `mkSem` URL query needs to be set to `2`.

**Comment by theodorusclarence** [comment]
Hi, I'm not actively maintaining this anymore, feel free to open a PR or contact @robbypambudi.

**Comment by robbypambudi** [comment]
Working In Progress @albugowy15 @theodorusclarence 

Sorry for the delay

**Comment by theodorusclarence** [comment]
@robbypambudi I think we can make it dynamic, check if current month is an odd/even semester

**Comment by robbypambudi** [comment]
I think that's a good idea. I'll work on this issue.
